# Site settings
author: harmonious-founder-9456
title: 
header-img: img/home-bg.png
email: marvelljgarrett@gmail.com
copyright_name: harmonious-founder-9456
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mgarrett2016

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
